# Generated by Django 5.2.7 on 2025-11-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leaverequest_leavetracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date']},
        ),
    ]
