# Generated by Django 5.2.7 on 2025-11-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_holiday_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={},
        ),
    ]
